/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginGUI;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import com.formdev.flatlaf.*;
import javax.swing.UIManager;

/**
 *
 * @author Kaitlyn
 */
public class loginGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginGUI.class.getName());

    /**
     * Creates new form loginGUI
     */
    
    int mousepX;
    int mousepY;
    
    public loginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Kaitlyn
    private void initComponents() {
        jPanel1 = new JPanel();
        exitButt = new JButton();
        page = new JPanel();
        pc_icon = new JLabel();
        jLabel3 = new JLabel();
        login = new JPanel();
        usernameField = new JTextField();
        passwordField = new JPasswordField();
        login_button = new JButton();
        seperator_u = new JSeparator();
        seperator_p = new JSeparator();
        icon_user = new JLabel();
        icon_pass = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("IPOS SA");
        setUndecorated(true);
        setPreferredSize(new Dimension(800, 400));
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                formMouseClicked(e);
            }
        });
        var contentPane = getContentPane();

        //======== jPanel1 ========
        {
            jPanel1.setBackground(new Color(0x333333));
            jPanel1.setToolTipText("");
            jPanel1.addMouseMotionListener(new MouseMotionAdapter() {
                @Override
                public void mouseDragged(MouseEvent e) {
                    jPanel1MouseDragged(e);
                }
            });
            jPanel1.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    jPanel1MousePressed(e);
                }
            });
            jPanel1.setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax . swing. border .EmptyBorder
            ( 0, 0 ,0 , 0) ,  "JF\u006frmDesi\u0067ner Ev\u0061luatio\u006e" , javax. swing .border . TitledBorder. CENTER ,javax . swing. border
            .TitledBorder . BOTTOM, new java. awt .Font ( "Dialo\u0067", java .awt . Font. BOLD ,12 ) ,java . awt
            . Color .red ) ,jPanel1. getBorder () ) ); jPanel1. addPropertyChangeListener( new java. beans .PropertyChangeListener ( ){ @Override public void
            propertyChange (java . beans. PropertyChangeEvent e) { if( "borde\u0072" .equals ( e. getPropertyName () ) )throw new RuntimeException( )
            ;} } );

            //---- exitButt ----
            exitButt.setText("X");
            exitButt.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    exitButtMouseClicked(e);
                }
            });
            exitButt.addActionListener(e -> exitButtActionPerformed(e));

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButt))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exitButt)
                        .addGap(0, 0, Short.MAX_VALUE))
            );
        }

        //======== page ========
        {
            page.setBackground(new Color(0xffcc66));

            //---- jLabel3 ----
            jLabel3.setFont(new Font("Colonna MT", Font.BOLD, 48));
            jLabel3.setForeground(new Color(0x333333));
            jLabel3.setText("IPOS SA");

            GroupLayout pageLayout = new GroupLayout(page);
            page.setLayout(pageLayout);
            pageLayout.setHorizontalGroup(
                pageLayout.createParallelGroup()
                    .addGroup(pageLayout.createSequentialGroup()
                        .addContainerGap(116, Short.MAX_VALUE)
                        .addGroup(pageLayout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, pageLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(111, 111, 111))
                            .addGroup(GroupLayout.Alignment.TRAILING, pageLayout.createSequentialGroup()
                                .addComponent(pc_icon)
                                .addGap(134, 134, 134))))
            );
            pageLayout.setVerticalGroup(
                pageLayout.createParallelGroup()
                    .addGroup(pageLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(pc_icon)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addContainerGap(66, Short.MAX_VALUE))
            );
        }

        //======== login ========
        {
            login.setBackground(Color.white);
            login.setPreferredSize(new Dimension(400, 400));

            //---- usernameField ----
            usernameField.setForeground(new Color(0x666666));
            usernameField.setText("Username");
            usernameField.setToolTipText("");
            usernameField.setBorder(null);
            usernameField.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    usernameFieldFocusGained(e);
                }
            });
            usernameField.addActionListener(e -> usernameFieldActionPerformed(e));

            //---- passwordField ----
            passwordField.setText("username");
            passwordField.setBorder(null);
            passwordField.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    passwordFieldFocusGained(e);
                }
            });
            passwordField.addActionListener(e -> passwordFieldActionPerformed(e));

            //---- login_button ----
            login_button.setText("LOGIN");
            login_button.addActionListener(e -> login_buttonActionPerformed(e));

            GroupLayout loginLayout = new GroupLayout(login);
            login.setLayout(loginLayout);
            loginLayout.setHorizontalGroup(
                loginLayout.createParallelGroup()
                    .addGroup(GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addContainerGap(86, Short.MAX_VALUE)
                        .addGroup(loginLayout.createParallelGroup()
                            .addComponent(icon_user, GroupLayout.Alignment.TRAILING)
                            .addComponent(icon_pass, GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(loginLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(login_button)
                            .addComponent(usernameField, GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField, GroupLayout.Alignment.LEADING)
                            .addComponent(seperator_u, GroupLayout.Alignment.LEADING)
                            .addComponent(seperator_p, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
            );
            loginLayout.setVerticalGroup(
                loginLayout.createParallelGroup()
                    .addGroup(GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addContainerGap(136, Short.MAX_VALUE)
                        .addGroup(loginLayout.createParallelGroup()
                            .addComponent(usernameField, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(icon_user, GroupLayout.Alignment.TRAILING))
                        .addGap(15, 15, 15)
                        .addComponent(seperator_u, GroupLayout.PREFERRED_SIZE, 5, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(loginLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(icon_pass))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seperator_p, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(login_button)
                        .addGap(119, 119, 119))
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(page, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(login, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(login, GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                        .addComponent(page, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_buttonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void exitButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_exitButtActionPerformed

    private void exitButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtMouseClicked

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        // TODO add your handling code here:
        passwordField.setText("");
    }//GEN-LAST:event_passwordFieldFocusGained

    private void usernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusGained
        // TODO add your handling code here:
        usernameField.setText("");
    }//GEN-LAST:event_usernameFieldFocusGained

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int cordX = evt.getXOnScreen();
        int cordY = evt.getYOnScreen();
        this.setLocation(cordX-mousepX, cordY-mousepY);
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
        
    }//GEN-LAST:event_jPanel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginGUI().setVisible(true);
            }
        });
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Kaitlyn
    private JPanel jPanel1;
    private JButton exitButt;
    private JPanel page;
    private JLabel pc_icon;
    private JLabel jLabel3;
    private JPanel login;
    private JTextField usernameField;
    private JPasswordField passwordField;
    private JButton login_button;
    private JSeparator seperator_u;
    private JSeparator seperator_p;
    private JLabel icon_user;
    private JLabel icon_pass;
    // End of variables declaration//GEN-END:variables
}
