package IPOS_Detailed_Design.model.enums;

public enum UserRole {
    ADMIN,
    DIRECTOR_OF_OPERATIONS,
    MERCHANT,
    SENIOR_ACCOUNTANT,
    ACCOUNTANT,
    WAREHOUSE_EMPLOYEE,
    DELIVERY_DEPARTMENT_EMPLOYEE
}